### ISSUE TITLE
Tray

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textosaurus#13]
**Suggestion**
Option to minimize/close **Textilosaurus** to tray. 'Settings' - 'Tools' - 'User interface' - new tab - 'Tray' with two check-boxes:

- _Minimize to tray_
- _Close to tray_

**Example**
If 'Minimize to tray' is not checked but 'Close to tray' is checked **Textilosaurus** would minimize to task bar and close to tray.

**Comment by martinrotter** [comment]
Should tray icon be available also when ALL Textosaurus editors are closed? So that it could act as "quick launcher" too?

**Comment by smaragdus** [comment]
@martinrotter 

> Should tray icon be available also when ALL Textosaurus editors are closed? So that it could act as "quick launcher" too?

For me after program has exited there is no need that the tray icon should continue to reside in system tray.  I usually launch programs with dedicated launchers.

I suppose tray icon should have some basic commands- Show/Settings/Exit, etc.

**Comment by martinrotter** [comment]
So you basically want tray to be able to HIDE Textosaurus main window so that is is entirely hiddne (not visible in main Windows panel)?

**Comment by smaragdus** [comment]
I think that on Window 'minimize to tray' is a common option- when enabled program goes to system tray on minimize (visible or invisible part),  when not enabled program goes to task bar on minimize. I think your [RSS Guard](https://github.com/martinrotter/rssguard) offers such options. On Linux it may be different though- as far as I know system tray has been completely removed from Gnome 3.

**Comment by martinrotter** [comment]
Yes, basically agree. Tray support will get added soon.

**Comment by martinrotter** [comment]
Please, test this on development build once it gets compiled.

**Comment by smaragdus** [comment]
**Textosaurus** version **0.9.0.0** crashes when I check **Enable Tray Icon** and click **Apply**, screen:

![textosaurus 0 9 0 0 - crash - 002](https://user-images.githubusercontent.com/9025757/38925849-72092aba-4309-11e8-83be-bec11e6e0eee.png)

**Comment by martinrotter** [comment]
Is that reproducible?

**Comment by martinrotter** [comment]
Added possible fix - https://github.com/martinrotter/textosaurus/commit/0f56dc0441a2f4c7b6c9c4e8f3815ae1e1b7760a

Please test once it gets compiled. Also, debugging log from crash would be nice.

**Comment by smaragdus** [comment]
> Added possible fix - [0f56dc0](https://github.com/martinrotter/textosaurus/commit/0f56dc0441a2f4c7b6c9c4e8f3815ae1e1b7760a)
> 
> Please test once it gets compiled. Also, debugging log from crash would be nice.

I will test it. Do the [Development builds](https://github.com/martinrotter/textosaurus/wiki/Development-builds) generate debug logs?

I can provide dump (**.dmp**) files but I don't know whether these dump files would be of any use.

**Comment by martinrotter** [comment]
Yes, I fixed the build (I had compilation error there), now it will build latest commit, dmp files could probably help. You just run textosaurus  like this - https://github.com/martinrotter/rssguard/wiki/Generating-debug-log-file

So, https://github.com/martinrotter/textosaurus/commit/43d51308b45a92cdb61bee0101c051cbce8fff77 is now the latest commit which should be available in "Development builds" in 15 minutes.

**Comment by martinrotter** [comment]
I managed to reproduce the issue on clean Windows 8 x64 (but suprisingly not on Windows 7 x64).

**Comment by smaragdus** [comment]
**Off-topic**
As you mentioned [RSS Guard](https://github.com/martinrotter/rssguard) I stopped using it some time ago because of severe problems with updating feeds. Are you willing to investigate problems I open new [issue](https://github.com/martinrotter/rssguard/issues)?

**Comment by smaragdus** [comment]
I tested [textosaurus-0.9.1-43d5130-win64](https://transfer.sh/Uw8Oa/textosaurus-0.9.1-43d5130-win64.7z) and there are no more crashes when I check **Enable Tray Icon**, problem seems fixed.

**Comment by smaragdus** [comment]
I tested [textosaurus-0.9.1-43d5130-win64](https://transfer.sh/Uw8Oa/textosaurus-0.9.1-43d5130-win64.7z) and there are no more crashes when I check **Enable Tray Icon**, problem seems fixed.

**Comment by martinrotter** [comment]
E-mail arrived, saying

> I tested textosaurus-0.9.1-43d5130-win64 and there are no more crashes when I check Enable Tray Icon, problem seems fixed.

But I do not see the comment here, can you confirm it is fixed?

**Comment by smaragdus** [comment]
It seems there was an issue with GitHub- I got duplicate comment, when I deleted one of the duplicates it seems the other also got deleted.

Yes, I will post the original comment below.

I tested [textosaurus-0.9.1-43d5130-win64](https://transfer.sh/Uw8Oa/textosaurus-0.9.1-43d5130-win64.7z) and there are no more crashes when I check Enable Tray Icon, problem seems fixed.

Since there are no more crashes and **textosaurus** behaves as expected you may close this issue.

**Comment by martinrotter** [comment]
> As you mentioned RSS Guard I stopped using it some time ago because of severe problems with updating feeds. Are you willing to investigate problems I open new issue?

Yes, open new issue, describe the situation in great detail. I will probably have to completely rewrite the feed update logic.
