### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textosaurus#20]
I had a look at [The Portable Freeware Forum](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=23638) discussion about the name of the program (I no longer comment there because of the severe censorship)- I don't like **Textilosaurus** very much (neither do I like the icon)- for me **Textilosaurus** implies rather **textile** than **text**. Below I will jot down my suggestions for new name if you decide to change it in the future.

- **inkpot**
- **inkwell**
- **jotpad**
- **jotter**
- **penpad**
- **quill**
- **scribbler**

All names are short and easy to remember. But if you decide to change the program name you should also change the program icon. My favourite of the above suggested is **inkpot**.

If you find this issue irrelevant feel free to close it.

**Comment by smaragdus** [comment]
> The problem is that I am not a designer, it was easy to find free-to-use "dinosaurus" icon. But what about "inkpot" icon?

Unfortunately I am not a graphic designer either so i cannot help. Yet I think that creating an original icon for your program would not require too much work by a designer.

What about opening a new issue "Icon" with "help-wanted" label? But I suppose that first you need to choose a name you really like.

**Comment by martinrotter** [comment]
I will postpone this. I feel that changing name is not actually needed in this stage of time. I would image it would makes sence once Textilosaurus becomes widely used, which is not the case, as it seems that it is used only by ~50 users right now. So I will focuse on new features for upcoming weeks.

**Comment by smaragdus** [comment]
> I will postpone this. I feel that changing name is not actually needed in this stage of time. I would image it would makes sence once Textilosaurus becomes widely used, which is not the case, as it seems that it is used only by ~50 users right now. So I will focuse on new features for upcoming weeks.

I think that it is much painful to rename a widely used and well-established program than one in early phase of development. For example browser [QupZilla](https://qupzilla.com/) was renamed to [Falkon](https://www.phoronix.com/scan.php?page=news_item&px=QupZilla-Becomes-Falkon) and this may cause issues. Anyway, I agree that polishing the program is more important than renaming it.

**Comment by martinrotter** [comment]
@smaragdus What do you think about "Tekstosaurus" or just "Textosaurus". None of these seems to be taken or used by major companies.
The bonus would be that we could still use icon based on "saurus". So some Dinosauruses!

What you think?

**Comment by FabioLolix** [comment]
I think that "Textosaurus" or "Textsaurus" would be good.

I have started packging this for the [AUR](https://aur.archlinux.org/packages/textilosaurus/) some days ago, and eventual name changes will be relevant in the future.

Actually last two version fails to compile but I'll open a dedicated issue for that

**Comment by martinrotter** [comment]
I see.

At this point, I think that Textosaurus or Tekstosaurus are my favorites. I will rename to one of them soon.

**Comment by martinrotter** [comment]
> Actually last two version fails to compile but I'll open a dedicated issue for that

Do it, I will fix. But, I have setup automatic Arch build and no errors are reported.

https://build.opensuse.org/package/show/home:skunkos:textilosaurus/textilousaurus-git

**Comment by martinrotter** [comment]
Renamed to "Textosaurus".

**Comment by smaragdus** [comment]
@martinrotter 
Sorry for the late response.
For me **Textosaurus** is better than **Textilosaurus**, thanks.
