### ISSUE TITLE
New tabs via left mouse double-click on tab bar does not work

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textosaurus#22]
@martinrotter 

![textosaurus 2018 03 05 - 2018-03-05 - 002](https://user-images.githubusercontent.com/9025757/36993738-7d7d20dc-20b7-11e8-8eb5-c0372dda8dc6.png)

Opening of new tabs with left mouse button double-click on tab bar does not work on my system (Windows 8 x64). Please confirm.

**Comment by martinrotter** [comment]
Fixed, test latest dev version from commit https://github.com/martinrotter/textosaurus/commit/3359d7d9f530a52600ef2629289b85d613df8f2f

**Comment by smaragdus** [comment]
@martinrotter 
Now double-clicking on tab bar opens new tab, fixed, thanks.
