### ISSUE TITLE
Exit from maximized state

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textosaurus#23]
@martinrotter 

When I exit **Textosaurus** from maximized window on restart it does not remember it and appears in minimized state- it remembers window size and position but not window state.

I expect that if **Textosaurus** is exited  in maximized state on restart it should open in maximized state too.

This happens under Windows 8 x64, please confirm.

**Comment by martinrotter** [comment]
I made a fix, can you please test latest development build from date 03-06-2018 or newer?

https://github.com/martinrotter/textosaurus/wiki/Development-builds

**Comment by smaragdus** [comment]
@martinrotter 
How I am supposed to download the Windows builds? The provided links do not work

**Comment by martinrotter** [comment]
https://transfer.sh/WsFct/textosaurus-2018.03.05-33c1fb7-win64.7z

**Comment by smaragdus** [comment]
@martinrotter 
After restart **Textosaurus** now remembers its window state- fixed, thanks.
