### ISSUE TITLE
Some URLs not detected

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textosaurus#25]
**Textosaurus** (as of version **2018.03.21**) fails to detect certain long URLs, screen:

![textosaurus 2018 03 21 - 2018-03-24 - 002](https://user-images.githubusercontent.com/9025757/37856520-898583ac-2efd-11e8-804d-7bde42e8faf5.png)

While another [Scintilla](http://win.softpedia.com/)-based editor- [Notepad3](https://www.rizonesoft.com/downloads/notepad3/), detects the same URL successfully, screen:

![notepad3 3 18 223 908 - 2018-03-24 - 003](https://user-images.githubusercontent.com/9025757/37856630-33fc8ab0-2efe-11e8-97a9-2fa3fe64b4b7.png)

[Example URL](https://www.gatestoneinstitute.org/search.php?cx=014255815713646959106%253Afcvl99skesi&cof=FORID%253A9&ie=UTF-8&q=Muslim+Persecution+of+Christians&sa=Search)

**Comment by martinrotter** [comment]
![screenshot 2018-03-26 07 42 56](https://user-images.githubusercontent.com/1255302/37888760-5201d912-30c9-11e8-9bc8-f6fb6522ead3.png)

**Comment by smaragdus** [comment]
Strange. This is under Windows?

**Comment by smaragdus** [comment]
Thanks for the fix.

**Comment by martinrotter** [comment]
Yes, it should be fixed, new binaries incoming in 10 minutes I guess.

**Comment by smaragdus** [comment]
I tested version **2018.03.26** and I can confirm that the problematic URLs are detected fine now, thanks.
