### ISSUE TITLE
Feature Request: Add support for macros

### ISSUE THREAD

**Issue by peterfilipek** [martinrotter/textosaurus#27]
Hello, it will be really great if you can add macros support.

**Comment by martinrotter** [comment]
I decided to add macros, these features will be supported:
* macro can be persistently and portably saved,
* macros could be (probably) assigned a keyboard shortcut (is this needed, @peterfilipek?),
* all internal Scintilla (editor) actions will be recordable to macros,
* new "Macros" sidebar" will be added, which will allow to:
    * start/stop macro recording,
    * save macro,
    * play just recorded macro,
    * see list of just recorded actions,
    * remove hand-picked actions from the list,
    * reorder recorded actions.

**Comment by peterfilipek** [comment]
Thanks for your offer but I don't want to overwhelm myself with unneeded new assigned keyboard shortcuts. This feature is not really needed.

**Comment by martinrotter** [comment]
That is what I actually thought myself. I will see when I get to implement it.

**Comment by peterfilipek** [comment]
At first glance it looks advanced and is easy to create new macro. Awesome work.

**Comment by martinrotter** [comment]
Now, I will add option to save recorded macro persistently. The question is from which would you prefer to access your saved macros:
 - There could be another "tab" in sidebar, called "Saved Macros", which your switch to and run macro from list (look similar to left FS sidebar, see bottom tabs).
 - Or that "MAcros" plugin can register menu which will appear in "Tools -> Macros (submenu) -> <HERE-SUBMENU-OF-SAVED-MACROS>.

I would prefer to put list of saved macros into the sidebar as well. What you think?

**Comment by peterfilipek** [comment]
I'd prefer Saved Macros in sidebar rather than in Tools menu.

**Comment by martinrotter** [comment]
![macros](https://user-images.githubusercontent.com/1255302/39920465-69df900c-5517-11e8-9899-44c9fb6d548a.gif)

**Comment by peterfilipek** [comment]
It looks fantastic! When I can dowload new realease :)

**Comment by martinrotter** [comment]
Development builds should be ready in a few minutes.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/textosaurus/wiki/Development-builds

**Comment by martinrotter** [comment]
Review it and let me know, how it went.

**Comment by peterfilipek** [comment]
Using Find and Replace dialog causes a crash.

**Comment by martinrotter** [comment]
What exact steps did you use to produce the issue?

**Comment by martinrotter** [comment]
Reproduced, will try to fix.

**Comment by martinrotter** [comment]
Crash should be fixed, dev. builds are compilling.

**Comment by martinrotter** [comment]
Couple of other stuff around macros were fixed like saving macros with non-unique name, removing stored macros etc. Just committed.

**Comment by peterfilipek** [comment]
The new development build works fine for me. But I noticed one thing.
![textosaurus-macro-sidebar-bottom](https://user-images.githubusercontent.com/37799536/39925738-1fbe9fb6-552d-11e8-83c4-eb9e84d1b6f4.png)
Buttons to switch between Stored Macros and Macro Recorder don't work.

**Comment by martinrotter** [comment]
You mean, those arrow buttons to move among tabs?

**Comment by martinrotter** [comment]
AFAIK, those buttons do not switch active tab by themselves, they only "move" tabbar, you need to click on tab header by yourself after you click on arrows. Not sure if I understand the problem correctly.

**Comment by peterfilipek** [comment]
![c1](https://user-images.githubusercontent.com/37799536/39926638-0f255c46-5530-11e8-8bcc-0dd2f9302dae.png)
Reducing the width of Macro sidebar leads to show up these arrow buttons.
![c2](https://user-images.githubusercontent.com/37799536/39926650-16009fee-5530-11e8-87c1-bb83f5067ecd.png)
And clicking on them does nothing. No switch from Stored Macros to Macro Recorder.

**Comment by peterfilipek** [comment]
I've tested Macros functionality a lot. I didn't find any bugs anymore and everything was running smooth.
I think it's great idea to short titles or replace titles with icons.

**Comment by martinrotter** [comment]
I shortened titles to "My Macros" and "Recorder". Closing this.
