### ISSUE TITLE
error: 3rd-party/scintilla

### ISSUE THREAD

**Issue by ivanbraga** [martinrotter/textosaurus#29]
How's it going, martinrotter? I hope you're well.
I have the following problem, unzipped the textsaurus-master.zip file, opened the project with QTCreator, and when I give the file to compile, I get the following error.

textsaurus-master/src/miscellaneous/settings.h: 13: error: 3rd-party/scintilla/include/Scintilla.h: File or directory not found

But by checking the folder "textsaurus-master / src / 3rd-party / scintilla". I see that it is empty.
How to solve this? Do I have to download some files from somewhere else and put them in this folder?

Thank you very much in advance.

**Comment by martinrotter** [comment]
Scintilla source code is included as Git [submodule](https://git-scm.com/docs/git-submodule). Problem is that if you push "Download ZIP" button on Github, then submodules won't be included in the ZIP.

So, to actually obtain full source code for compilation, you have to [clone](https://git-scm.com/docs/git-clone) repository and fetch all submodules. Like this:

```bash
cd C:\
git clone https://github.com/martinrotter/textosaurus.git
cd textosaurus
git submodule update --init --recursive
```
So, you need to have Git client installed and run those commands in Git command line.
