### ISSUE TITLE
Bug - Syntax highlighting does not work

### ISSUE THREAD

**Issue by skyide** [martinrotter/textosaurus#30]
Hi Martin

Ok so I am using the latest TT version **textosaurus-2018.04.11-5c28a15-linux64.AppImage** and I have noticed that syntax coloring does not work. When I open up a C++ source file, there is no syntax highlighting and when you go to Language->C->C++, still no coloring.

This is something strange I just noticed.

**Comment by martinrotter** [comment]
I will test AppImage tonight on home linux PC.

**Comment by martinrotter** [comment]
I was not able to reproduce the issue, please, answer questions above.

**Comment by skyide** [comment]
Sorry I was unable to reply any earlier. Please see attached zip file. It has a small video + the settings you requested,..
[files.tar.gz](https://github.com/martinrotter/textosaurus/files/1902100/files.tar.gz)

**Comment by skyide** [comment]
I actually don't remember if it worked before. See the attached zip file and let me know if you need any other files.

**Comment by skyide** [comment]
Oh dear...my fault, I was using TT's default editor theme, after I changed it, see what you get.
![theme](https://user-images.githubusercontent.com/22862491/38671885-f1719fcc-3e8f-11e8-8fe4-29f8db31538e.png)

**Comment by martinrotter** [comment]
Yes, default theme is mainly optimized for speed, so it does not have "substyles" for syntax highlighting enabled. You have to use another color scheme to get syntax highlighting. Cheers.
