### ISSUE TITLE
Sidebar width too large

### ISSUE THREAD

**Issue by Jarco** [martinrotter/textosaurus#36]
#### The sidebar is to large (width) I can only make it larger but not smaller

The sidebar takes up about 40% of my screen. I can drag it wider, but I cannot make it smaller. 

#### How to reproduce the bug?

1. Install textosaurus
2. Try to drag the width of the filesystem sidebar smaller then the default.

#### What is the expected result?
The sidebar becomes smaller.

#### What actually happened?

It didn't become smaller.

**Comment by martinrotter** [comment]
I made some tweaking to sidebars minimum size behavior. Can you test development build for https://github.com/martinrotter/textosaurus/commit/cdd3be7028934987bd6d14b3fefdcbdec64c56f6?

You can find link in wiki/dev. builds. Make sure the build is for the commit written above or newer.

**Comment by Jarco** [comment]
First of, apologies for not providing all of the information. (Manjaro Linux, KDE, HD)
Secondly cdd3be7 fixed the issue. So this is fixed.
