### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [martinrotter/textosaurus#37]
#### How to reproduce the bug?

1. Launch Ubuntu 14.04 Live ISO
2. Download textosaurus AppImage
3. Try to run

#### What is the expected result?

Runs

#### What actually happened?

Does not run

#### Other information (logs, see Wiki)

AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-7145/usr/bin/../lib/libtextosaurus.so)

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

Reference: https://github.com/AppImage/appimage.github.io/pull/537

**Comment by martinrotter** [comment]
Textosaurus requires GCC 7 and is compiled on Ubuntu 14.04 image on Travis CI platform.

**Comment by martinrotter** [comment]
Perhaps switch to clang would help?

**Comment by probonopd** [comment]
> Perhaps switch to clang would help?

I don't know but It is important that either no newer llibstdc++ is pulled in than what comes with trusty out-of-the box, or that something like [this](https://github.com/darealshinji/AppImageKit-checkrt/issues/1#issuecomment-370134384) is used.

**Comment by probonopd** [comment]
What does `set -- T*.AppImage` do?

**Comment by probonopd** [comment]
The test build is working for me. Thank you very much!

**Comment by martinrotter** [comment]
:) Nice. Closing.

**Comment by martinrotter** [comment]
Btw: http://linuxcommand.org/lc3_man_pages/seth.html
