### ISSUE TITLE
Keyword highlighting improvement and new functionality

### ISSUE THREAD

**Issue by severach** [martinrotter/textosaurus#38]
Keyword highlighting: mark a word and all words like it are highlighted.

Notepad++ has two different methods of keyword highlighting, marking a word with mouse or keyboard, and Style Token from the right click menu.

    tape
    tapestry
    tapered
    tape recorder

Mark `tape` on the first line with the mouse and we should only see highlights on lines 1,4 because mouse marking must be word based. This is necessary because many languages have single letter variables and we need to see where they all are without the false positives from any word that contains the letter. The Notepadqq crew disallowed highlights from single letter marking because is it so utterly useless to see every occurrence of a single letter all over the screen.

Mark tape on the second line with Style Token and we should see highlights on all 4 lines because Style Token is text based, not word based. This allows word prefixes to be highlighted without having to be words.

Another distinction is that mouse marking is case insensitive. Style token is case sensitive.

Style Token is additive. A token can be styled with all 5 colors and the color is some sort of sum of the selected colors.

Requests: Change mouse marking to be word based. Add non word based Style Token.

**Comment by martinrotter** [comment]
Hello, brother.

I see, I have actually never really used context-aware keyword highlighting. Maybe I could add some key to modify the behavior of current feature implementation.

For example pressing `ALT` and selecting some text could triggier CONTEXT-AWARE highlighting, while current usage (without `ALT` being pressed, just selections) would be kept.

What you think?

**Comment by severach** [comment]
Cinnamon hijacks Alt-Mouse for move window. Alt-Mouse Alt-Shift-Arrow is usually used for column marking. Having to use a key would make it hard to discover and would make the functionality different than Notepad++. A config option would be better. Non whole word styling will be provided by "Style Token."

I like the live styling while dragging across text. One option is to live style non word based text while drag/shift and when the drag/shift is released the non whole words are unstyled and only the whole words remain styled. Marking part of a word only to have it unstyled when the mouse is released may cause bug reports.

Another option is to do both based on what has been marked. If the marked text is not a whole word then style non whole word text. If the marked text is a whole word then only style whole words. To let the user know that what is marked changes the style method you should distinguish the two styling methods in some way, maybe with a different color.

**Comment by severach** [comment]
That sounds good.

**Comment by martinrotter** [comment]
https://streamable.com/4bngv

**Comment by martinrotter** [comment]
Can you test the feature in latest development release for commit 081ae54?

**Comment by martinrotter** [comment]
@severach ping
