### ISSUE TITLE
Do not allow to open one file in multiple editors/tabs

### ISSUE THREAD

**Issue by pellicus** [martinrotter/textosaurus#49]
I have multiple tabs on the same file X , let say t0 , t1 , t2
if i modify and save working on t1 i get a pop up saying me that the file in t0 is modified from an external 
editor , after that i get another pop up for tab t2. 

double clicking on the same file open multiple tabs

proposal:
- double clicking on a already opened file just select the right tab.
- adding a menu command to duplicate the current tab. (even if it's rarely useful)
- avoid the pop up in case of saving from textosaurus (tracking the saved files in a map to clean after everything is saved and tabs are finally synced)

**Comment by martinrotter** [comment]
I added detection of already opened files which is now used to open file in existing tab if there is one. Please, test.
