### ISSUE TITLE
Having Build Issues with "3rd-party" Scintilla

### ISSUE THREAD

**Issue by johjeff** [martinrotter/textosaurus#50]
#### Brief description of the issue.

Following the build steps in build.pro, I get the following warning and error:

qmake:
WARNING: Failure to find: 3rd-party/scintilla/qt/ScintillaEdit/ScintillaDocument.h

make:
In file included from ../../../src/libtextosaurus/common/dynamic-shortcuts/dynamicshortcuts.cpp:5:
../../../src/libtextosaurus/common/miscellaneous/settings.h:13:10: fatal error: 3rd-party/scintilla/include/Scintilla.h: No such file or directory
 #include "3rd-party/scintilla/include/Scintilla.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2040: dynamicshortcuts.o] Error 1
make[1]: Leaving directory '/home/jeffreyj/Downloads/tmp/textosaurus/textosaurus/build-dir/src/libtextosaurus'
make: *** [Makefile:46: sub-src-libtextosaurus-make_first-ordered] Error 2

#### How to reproduce the bug?

1. git clone https://github.com/martinrotter/textosaurus.git
2. mkdir textosaurus/build-dir && cd textosaurus/build-dir
3. qmake-qt5 ../build.pro -r "CONFIG+=release" "PREFIX=./usr"
              WARNINGs
4. make
              Error

#### What is the expected result?

That the project be built and that the 3rd-party scintilla directory have the relevant files in it.

#### What actually happened?

qmake produces a warning about not finding files in 3rd-party
make errors out

#### Other information (logs, see Wiki)

[warning.txt](https://github.com/martinrotter/textosaurus/files/2386012/warning.txt)
[error.txt](https://github.com/martinrotter/textosaurus/files/2386013/error.txt)

**Comment by martinrotter** [comment]
`git submodule update --init --recursive`
