### ISSUE TITLE
Standard installer does not install MSVCP140, textosaurus not showing in installed programs

### ISSUE THREAD

**Issue by kostadinnm** [martinrotter/textosaurus#53]
Hello

Straight on the issue: just after installing textosaurus on a windows(virtual ver.7 in this instance) and trying to launch the program it breaks with the following error: 

> The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem.

Here's a screenshot:
![2018-10-21 10_34_02-textosaurus exe - system error](https://user-images.githubusercontent.com/18436405/47264349-d8a10800-d51d-11e8-8282-22ba915afa4b.jpg)

After extracting the _**vc_redist.x64.exe**_ from _**textosaurus-\*.\*.\*-\*\*\*\*\*\*\*-win64.exe**_ and installing it textosaurus loads normally.

As a side remark, it doesn't show up in the installed programs section in control panel, although everything is ok in the start menu:

![2018-10-21 11_02_38-greenshot](https://user-images.githubusercontent.com/18436405/47264494-fa4fbe80-d520-11e8-9c1f-13aac7d1d19b.jpg)

Kind regards,
Kostadin

**Comment by martinrotter** [comment]
Yes, at this point, installer does not actually install vcredist, but vcredist installer is unpacked to target directory and user can install it on his own.

I will auto-install vcredist silently during Textosaurus installation.

> As a side remark, it doesn't show up in the installed programs section in control panel, although everything is ok in the start menu:

This is actually a feature. I wanted to keep installer "light" and do not pollute target system, therefore I decided to not create all those messy registry uninstall entries. You can always just uninstall the app by executing `Textosaurus\Uninstall.exe` file. Do you feel that having Textosaurus entry in Add/Remove programs would really help a lot?

**Comment by kostadinnm** [comment]
On the redist pack - feel free to close this issue when the vcredist-installer gets auto-activated.
On the add/remove entry - I personally don't mind it, as I tend to use most of the programs as portables. On my main system textosaurus is just the unpacked zip folder. But I have some other machines that are expected to have that default behavior.
