### ISSUE TITLE
Multi editing becomes single cursor editing whenever the cursor is moved

### ISSUE THREAD

**Issue by resotek** [martinrotter/textosaurus#55]
#### Brief description of the issue.
Multi-line editing does not allow cursor movement; it only seems to allow typing.

#### How to reproduce the bug?

1. With multiple lines of text in the editor, hold the alt key and drag down multiple lines with the mouse. You should see a cursor on each line.
2. Start typing. Your typing should show up on all lines, at the cursor.
3. Press either home, end, an arrow key, or control-arrow key to move one word right or left. Now you only have a single cursor.
#### What is the expected result?
I expected the same [multi-editing as Notepad++](https://notepad-plus-plus.org/features/multi-editing.html), where the cursors can be in different columns on different lines, and that multi-line editing would allow the user to move all cursors simultaneously using any cursor movement key, such as home, end, arrow keys, or control arrow keys (next/previous word).

#### What actually happened?
Cursor movement keys cause the multiple line cursor to become a single cursor.

#### Other information (logs, see Wiki)
Multi-editing is very valuable for reformatting text when search and replace will not do the job. The cursor movement keys are essential for this. Block editing is not a suitable replacement for multi-cursor editing because block editing requires the text to be vertically aligned, where the cursor is in the same column position on each line. Multi-editing has no such constraint.

**Comment by martinrotter** [comment]
I believe this is an upstream bug, because Scite behaves the same way. Notepad++ probably has some patches for this.

Interestingly:
* if you click (while `CTRL` is pressed too) on multiple lines -> now multiple text cursors appear -> move cursor with keys -> **WORKS**.
* if you make rectangular selection with `ALT` -> now multiple text cursors appear -> move cursor with keys -> **DOES NOT WORK**.

**Comment by resotek** [comment]
Dragging the mouse while holding `Alt`, or `Ctrl-Alt,` seems to be the only way to obtain multiple cursors on every line without having to click on each line individually, but then cursor movement is lost. Often when I use multiple cursors, it is on a vertical column spanning eight or more consecutive lines. It seems that the only way to obtain movable cursors on multiple consecutive lines is to `Ctrl click` on each desired cursor location individually, which is tedious if many cursors are desired. There should be a way to `click-drag` to select a vertical line of many cursors, and an `Alt` drag or `Ctrl-Alt` drag are the most intuitive means of doing that. Attempting that was in fact how I discovered the issue.

**Comment by resotek** [comment]
I had never heard of textosaurus before yesterday, when I discovered it with the command 'flatpak search notepad` while looking for a light-weight editor with multiple cursor support. Even though there is no mention of multi-editing or multiple cursors in the Features section of `README.md`, I took a chance and installed it because of references to Notepad++ and QScintilla, in the hope that textosaurus had multiple cursor editing. 

Multiple cursor editing is a very popular feature worthy of prominence with its own bullet in the Features section. I urge you to add it to `README.md`, as it will certainly attract more users.

**Comment by martinrotter** [comment]
Adding to readme right now. Pls report bug upstream and let me know :)

**Comment by martinrotter** [comment]
I double-checked behavior in Notepad++ (latest version) and compared to Textosaurus and I discovered that on my machine, multi-selections-cursors behave **WORSE** on Notepad++. No matter what I do, my multi-cursors become single cursor when i hit arrow button on my keyboard.

Textosaurus atleast preserves multi-cursors when used with `CTRL`, but when rectangular selections are made with mouse and `ALT`, then press some arrow, then both editors fail. See gifs below.

This must be upstream issue, nothing I can do at this point.

![multi](https://user-images.githubusercontent.com/1255302/47837532-b2e0f200-ddac-11e8-952b-1ee8c78178f7.gif)

**Comment by resotek** [comment]
>  Textosaurus atleast preserves multi-cursors when used with `CTRL`, but when rectangular selections are made with mouse and `ALT`, then press some arrow, then both editors fail.
I agree, and I understand that you cannot change the block edit behavior. I think the most sensible workaround is to enable the ability to add multiple cursors with a `CTRL` mouse drag, rather than the current default behavior, whereby a vertical `CTRL` mouse drag selects text in the same manner as a regular mouse drag. Are you able to override that behavior? This would enable adding multiple cursors without having to click on each line individually.

**Comment by resotek** [comment]
> Pls report bug upstream and let me know :)

I will test Scite and submit through there.

**Comment by resotek** [comment]
I just added this to Scintilla: 

[[bugs:#2060](https://sourceforge.net/p/scintilla/bugs/2060/)] In rectangular block edit mode, cursor keys should not exit into single cursor mode
