### ISSUE TITLE
string_view is only available with C++17

### ISSUE THREAD

**Issue by borneq** [martinrotter/textosaurus#67]
#### Brief description of the issue.
In C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\string_view:11 is error:
#if !_HAS_CXX17
 #error string_view is only available with C++17.
#endif /* _HAS_CXX17 */

I tried 
CONFIG += c++17
QMAKE_CXXFLAGS += -std=c++17
in build.pro 
and 
CONFIG += c++1z
CONFIG += c++17
QMAKE_CXXFLAGS += -std=c++17
in libtextosaurus.pro
but this not helps.

**Comment by martinrotter** [comment]
Must be something in configuration of your build tools, because compilation just works with vanilla MSVC 2017.

Also the flag to force use of latest available C++ specs is already set [here](https://github.com/martinrotter/textosaurus/blob/master/pri/build_opts.pri#L1).

**Comment by martinrotter** [comment]
I stumbled upon this too!!!! It had to somehow arose when I updated my MSVC toolchain.

Anyway, its fixed now!!!
