### ISSUE TITLE
Textosaurus Opens a LNK file instead of using it to redirect to different folder

### ISSUE THREAD

**Issue by gcs303** [martinrotter/textosaurus#73]
#### Brief description of the issue.

Textosaurus opens the content of a lnk file instead of using it to go to the directory the user is wishing to get to.

#### How to reproduce the bug?

1. Start with Open FIle
2. Click on a lnk file (create one if you do not have one)
3. See that the file is opened in Textosaurus

#### What is the expected result?

Use the lnk file to get to the folder it links to.

#### What actually happened?

The lnk file is opened in Textosaurus

#### Other information (logs, see Wiki)

None neede. Simple problem and fix.

**Comment by martinrotter** [comment]
What do you mean with 

> to get to the folder it links to

How could Textosaurus display a "folder"? You mean open the folder in "Filesystem" sidebar?

**Comment by martinrotter** [comment]
773602e - fixed opening LNK file, now the target file is opened instead. Not sure about LNK pointing to folders.

**Comment by gcs303** [comment]
>"What do you mean with"

>"to get to the folder it links to"

>"How could Textosaurus display a "folder"? You mean open the folder in "Filesystem" sidebar?"
When you use the menu File | Open File, the contents of a folder is displayed, where a user can select a file to open in the editor. If that initial folder has a LNK file (shortcut) in it that points to another folder, clicking on the shortcut should then display the contents of that second folder where the user can select a file (or another shortcut).i.e.,If an actual file is selected, it should be opened in the editor. If a LNK (shortcut) is selected, it should not be opened in the editor, but instead display the contents of the folder it points to. This is standard procedure with editors. A text editor should never see the contents of the actual LNK file itself. The reason LNK files (shortcuts) exist is for this very purpose. I use shortcuts to get to the right drive/folder/file all the time. All of my text editors can handle the LNK files just fine. In some cases, I might click on 4 or 5 LNK files before reaching my destination folder where I then choose the file I want to open. That is what they are for.
>"How could Textosaurus display a "folder"?
It does not mean that Textosaurus should display the folder as if it were a file, but instead display the contents the same way as an initial File | Open file command does.
You mean open the folder in "Filesystem" sidebar?"
No, it has nothing to do with the Filesystem sidebar.
To test, make sure you have a standard windows LNK file pointing to a folder (not a file). In Windows, right click on a folder and drag it to a different folder. When you release the mouse, a popup menu will appear with the last choice before "Cancel" being "Create shortcuts here." Choose the "Create shortcuts here" and you then have a shortcut that points to a folder (not a file). Any standard/common program with a File | Open file operation should be able to redirect to the new folder, not open the actual LNK shortcut file.
I was going to test the new builds but the links are not working:On URL: https://github.com/martinrotter/textosaurus/wiki/Development-buildsclicking on 773602e shows:https://transfer.sh/My6Ez/textosaurus-0.9.13-773602e-win64.7z
is a non-existent file.
Thanks for looking at this show-stopper bug, and Best of luck to you.    On Friday, December 6, 2019, 03:22:30 PM EST, martinrotter <notifications@github.com> wrote:  
 
 
What do you mean with


to get to the folder it links to


How could Textosaurus display a "folder"? You mean open the folder in "Filesystem" sidebar?

**Comment by martinrotter** [comment]
Pls, try it now - i changed a "open file" dialog behavior a bit, commit 507f3fb

latest dev version, see wiki, try and let me know
