### ISSUE TITLE
Feature request: make default date format user customizable

### ISSUE THREAD

**Issue by midaspt** [martinrotter/textosaurus#75]
#### Brief description of the issue.

In v0.9.12, **Textosaurus** date format defaults to "_11/19/19_" (_Month/Day/Year_), which is not only very confusing for non-US users but also a standard with a very limited applicability.

While the **.LOG** date format can be customized via "_Settings | Editor | General_" there is no such option for the default date format.

While the "_Tools | DateTime | Insert DateTime (Custom Format)_" menu option can easily be used to work around this limitation, it will prompt the user every time it is used for the format to be used -- and it currently defaults to "_HH:mm:ss dddd, dd.MM.yyyy_".

"_Tools | DateTime | Insert DateTime_" will insert a valid formatted **ISO** (**8601**, cf. <https://en.wikipedia.org/wiki/ISO_8601>) DateTime string, although the inclusion of alphabetic characters and arbitrary string separators makes it less suitable for processing CSV files meant for spreadsheet conversion.

#### How to reproduce the bug?

1. Access menu "_Tools | DateTime | Insert DateTime_"
2. '_11/19/19_' gets inserted into edited document at cursor point; selection isn't overwritten.

#### What is the expected result?

Insertion of '_2019-11-19_'. Selection overwritten. (string separators optional)

#### What actually happened?

See above.

#### Other information

Menu "_Tools | DateTime | Insert Time_" defaults to "_11:30 AM_", a standard valid only in Anglo-saxon cultures and in Japan.

**Comment by martinrotter** [comment]
So, i made some commits, please test latest dev version when it gets compiled (after 15 mins):
- selection is now automatically replaced if there is any for datetime functions (and this functionality is now available to all tools, even custom defined in settings)
- all datetime functions now respect active application locale
- all "prompt" values intered to "insert custom datetime" tool are now persistently saved and reloaded when the tool is triggered again - this feature is now also active for all tools

**Comment by midaspt** [comment]
Tested. Much better, at least for the "_Insert DateTime (Custom Format)_", which is indeed sticky now. Remaining _DateTime_ options behave as before, though.

Moreover, I defined '**F5**' as a custom keyboard shortcut for "_Insert DateTime (Custom Format)_", but it still requires an additional '**Enter**' press to get the value inserted.

That shouldn't be required, it's cumbersome; if a user isn't satisfied with the format currently set, he can always use the menu option to change it, IMHO.

**Comment by martinrotter** [comment]
@midaspt 

>Remaining DateTime options behave as before, though, my system locale notwithstanding.

Currently, "DateTime" methods use application locale, not system locale. Do you think using system locale and ignoring application locale would make sense?

>Moreover, I defined 'F5' as a custom keyboard shortcut for "Insert DateTime (Custom Format)", but it still requires an additional 'Enter' press to get the value inserted.

Yes, tools behave exactly the same, no matter if you launch it from shortcut or from the menu. I will think about this.

**Comment by midaspt** [comment]
> Currently, "DateTime" methods use application locale, not system locale. Do you think using system locale and ignoring application locale would make sense?

I don't clearly grasp the difference between the two but if you have to rely on obscure system settings it would make sense to at least rely on those more readily exposed to user customization.

In the end, it would be simpler to just set some defaults and allow the user to change those in the program if he's not content.
 
> > Moreover, I defined 'F5' as a custom keyboard shortcut for "_Insert DateTime (Custom Format)_", but it still requires an additional 'Enter' press to get the value inserted.
> 
> Yes, tools behave exactly the same, no matter if you launch it from shortcut or from the menu. I will think about this.

I am focusing exclusively on this _DateTime_ feature ("_do one thing but do it well_") and that's the way it works in all other text editors out there. Trust me, I have tried a few. ;)

**Comment by martinrotter** [comment]
8776b80

**Comment by martinrotter** [comment]
8776b80

**Comment by martinrotter** [comment]
OK, fixed this. Now DateTime methods use SYSTEM locale, custom format for the DateTime tool is now NOT requested via popup dialog but can be changeable in app settings "Editor" tab.

**Comment by martinrotter** [comment]
1878b12

**Comment by martinrotter** [comment]
Please test and let me know.

**Comment by midaspt** [comment]
Tested all "_Tools | DateTime_" options from '_textosaurus-0.9.13-1878b12-win64.7z_' with both blank and a custom set format. Works perfectly, at least for me. Thanks for considering my suggestions. :))

P.S.: For enhanced user-friendliness, you might wanna link, either from help or from the settings tab itself, to the appropriate syntax for changing these values. E.g., a resource like <https://www.php.net/manual/en/function.date.php> or such would do nicely.
