### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by cup** [martinrotter/textosaurus#77]
It seems that syntax highlighting is not supported.

If I open a file `sunday.cpp`, its just black and white.

**Comment by martinrotter** [comment]
Hello, Textosaurus surely supports syntax highlighting for C++.

![image](https://user-images.githubusercontent.com/1255302/71645286-61950100-2cd6-11ea-89a7-1342d8458811.png)

Make sure that you have some "editor color scheme activated".

![image](https://user-images.githubusercontent.com/1255302/71645296-88533780-2cd6-11ea-95fe-b6f242c50a3d.png)

Default "Textosaurus" color scheme disables almost all syntax highlighting substyles for good-by-default performance. You have to activate different color scheme, or customize it according to your needs.

Let me know if this helped you.

**Comment by cup** [comment]
Yes that fixes it, thank you. I think "Textosaurus (built-in theme)" should not be default, as it gives impression that syntax highlighting is not available. If user desire performance then can then choose Textosaurus theme. Thanks again

**Comment by martinrotter** [comment]
I changed default theme to Solarized Dark.

**Comment by cup** [comment]
thank you @martinrotter !
