### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by cup** [martinrotter/textosaurus#79]
It seems Textosaurus uses quite a bit of memory. For example with version
0.9.13, with no file open, and all the panes closed, and minimized, memory usage
is 24 MB.

Compare with other programs that use about 3 MB:

https://github.com/ProgerXP/Notepad2e

**Comment by martinrotter** [comment]
Hello, reason is probably simple. Notepad2e uses just winapi for gui, which makes it very lightweight app which is for Windows only. Textosaurus heavily relies on Qt libraries which are used for gui, network etc. Textosaurus runs on win, macosx, linux, os2...

Ram usage means nothing. Textosaurus should be similarly fast as N2e. If not let me know. Might be a bug.
