### ISSUE TITLE
Feature Request: Add variable to get the full path to the active file

### ISSUE THREAD

**Issue by peterfilipek** [martinrotter/textosaurus#81]
It would be really nice if there was a ability to get the full path to the active file for scripts in external Tools. Entering full script for each external tool is amazing feature but standard input - stdin - is not always very inconvenient way. I suggest something similar to variables in Notepad++ allowing access in run script to get full path to the active file, active file's directory, active file's name, filename without extension and extension.

$(FULL_CURRENT_PATH)   : E:\my Web\main\welcome.html
$(CURRENT_DIRECTORY)   : E:\my Web\main\
$(FILE_NAME)           : welcome.html
$(NAME_PART)           : welcome
$(EXT_PART)            : html

Via [https://npp-user-manual.org/docs/config-files/](https://npp-user-manual.org/docs/config-files/)

**Comment by martinrotter** [comment]
@peterfilipek 

Pls, test https://github.com/martinrotter/textosaurus/commit/de366b403ba181c14479fb7c6e77499ab4342ea5#diff-30cadf717dc31f54fe4b0379e2d875acR54

**Comment by peterfilipek** [comment]
Thank you, it works fine in Fedora 31.
